import { Contestant } from "@/src/types";

export const LEADERBOARD_DATA: Contestant[] = [
  {
    id: "1",
    rank: 1,
    avatar: "🧑‍💻",
    name: "Aryan Kapoor",
    handle: "@aryan.k",
    country: "India",
    flag: "🇮🇳",
    university: "IIT Bombay",
    niScore: 9847,
    scoreChange: 142,
    categories: ["tech", "research"],
    tags: ["tech", "research"],
    bio: "Full-stack engineer & ML researcher. Published 3 papers on transformer architectures. Building the future one commit at a time.",
    followers: 12400,
    following: 342,
    rankPercentile: "Top 0.01%",
    joinedDate: "Jan 2024",
    skills: [
      { label: "Code", value: 98, color: "#1A56FF" },
      { label: "Research", value: 94, color: "#00BE6A" },
      { label: "Collab", value: 87, color: "#FF4500" },
    ],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 94, weight: "25%", description: "GPA, coursework, academic awards", color: "#1A56FF", items: ["GPA 3.97/4.0", "Dean's List ×6", "Academic Excellence Award"] },
      { id: "research", name: "Research", icon: "🔬", score: 91, weight: "25%", description: "Papers, citations, contributions", color: "#00BE6A", items: ["3 Published Papers", "47 Citations", "ICLR 2024 Spotlight"] },
      { id: "code", name: "Code", icon: "💻", score: 98, weight: "20%", description: "GitHub activity, open source", color: "#9333EA", items: ["2,847 Contributions", "12 Stars Repos", "Top 1% GitHub"] },
      { id: "creator", name: "Creator", icon: "✨", score: 72, weight: "15%", description: "Content, courses, tutorials", color: "#F5A200", items: ["4 Technical Blogs", "1.2k Followers"] },
      { id: "social", name: "Social", icon: "🤝", score: 83, weight: "15%", description: "Community, mentoring, impact", color: "#FF4500", items: ["Mentor 14 Students", "Hackathon Judge"] },
    ],
    achievements: [
      { id: "a1", icon: "🏆", title: "Google Summer of Code 2024", date: "Jun 2024" },
      { id: "a2", icon: "📄", title: "ICLR 2024 — Spotlight Paper", date: "May 2024" },
      { id: "a3", icon: "🥇", title: "HackMIT 2024 — 1st Place", date: "Sep 2024" },
      { id: "a4", icon: "⭐", title: "GitHub Star Developer", date: "Mar 2024" },
    ],
    socials: [
      { platform: "GitHub", handle: "@aryankapoor", url: "#" },
      { platform: "LinkedIn", handle: "aryan-kapoor", url: "#" },
      { platform: "X", handle: "@aryan_builds", url: "#" },
    ],
  },
  {
    id: "2",
    rank: 2,
    avatar: "👩‍🔬",
    name: "Sofia Martínez",
    handle: "@sofia.m",
    country: "Spain",
    flag: "🇪🇸",
    university: "MIT",
    niScore: 9621,
    scoreChange: 89,
    categories: ["research", "tech"],
    tags: ["research", "tech"],
    bio: "Computational biologist. PhD candidate at MIT. Passionate about using AI to cure disease.",
    followers: 9800,
    following: 211,
    rankPercentile: "Top 0.02%",
    joinedDate: "Feb 2024",
    skills: [
      { label: "Research", value: 97, color: "#00BE6A" },
      { label: "Code", value: 89, color: "#1A56FF" },
      { label: "Writing", value: 92, color: "#9333EA" },
    ],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 97, weight: "25%", description: "GPA, coursework, academic awards", color: "#1A56FF", items: ["PhD Candidate MIT", "NSF Fellowship", "Summa Cum Laude"] },
      { id: "research", name: "Research", icon: "🔬", score: 96, weight: "25%", description: "Papers, citations, contributions", color: "#00BE6A", items: ["8 Published Papers", "124 Citations", "Nature Methods 2024"] },
      { id: "code", name: "Code", icon: "💻", score: 84, weight: "20%", description: "GitHub activity, open source", color: "#9333EA", items: ["1,203 Contributions", "3 OSS Tools"] },
      { id: "creator", name: "Creator", icon: "✨", score: 68, weight: "15%", description: "Content, courses, tutorials", color: "#F5A200", items: ["Science Communicator", "TEDx Speaker"] },
      { id: "social", name: "Social", icon: "🤝", score: 79, weight: "15%", description: "Community, mentoring, impact", color: "#FF4500", items: ["Women in STEM Mentor", "Lab Lead"] },
    ],
    achievements: [
      { id: "a1", icon: "🏅", title: "NSF Graduate Research Fellowship", date: "Sep 2023" },
      { id: "a2", icon: "📄", title: "Nature Methods Publication", date: "Apr 2024" },
      { id: "a3", icon: "🎤", title: "TEDx MIT Speaker", date: "Nov 2024" },
    ],
    socials: [
      { platform: "GitHub", handle: "@sofiamtz", url: "#" },
      { platform: "Scholar", handle: "Sofia Martínez", url: "#" },
    ],
  },
  {
    id: "3",
    rank: 3,
    avatar: "🎮",
    name: "Kenji Nakamura",
    handle: "@kenji.n",
    country: "Japan",
    flag: "🇯🇵",
    university: "Tokyo University",
    niScore: 9388,
    scoreChange: -23,
    categories: ["gaming", "tech"],
    tags: ["gaming", "tech"],
    bio: "Competitive programmer & game developer. Two-time ICPC World Finalist. Building indie games on the side.",
    followers: 7200,
    following: 178,
    rankPercentile: "Top 0.05%",
    joinedDate: "Mar 2024",
    skills: [
      { label: "Algorithms", value: 99, color: "#1A56FF" },
      { label: "Code", value: 96, color: "#9333EA" },
      { label: "Design", value: 71, color: "#F5A200" },
    ],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 88, weight: "25%", description: "GPA, coursework, academic awards", color: "#1A56FF", items: ["GPA 3.9/4.0", "CS Olympiad Gold"] },
      { id: "research", name: "Research", icon: "🔬", score: 72, weight: "25%", description: "Papers, citations, contributions", color: "#00BE6A", items: ["2 Conference Papers", "15 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 99, weight: "20%", description: "GitHub activity, open source", color: "#9333EA", items: ["ICPC 2-time Finalist", "LeetCode Top 50", "Codeforces 3200+"] },
      { id: "creator", name: "Creator", icon: "✨", score: 81, weight: "15%", description: "Content, courses, tutorials", color: "#F5A200", items: ["Indie Game Dev", "15k Steam Wishlist"] },
      { id: "social", name: "Social", icon: "🤝", score: 74, weight: "15%", description: "Community, mentoring, impact", color: "#FF4500", items: ["CP Community Lead", "Algorithm Tutor"] },
    ],
    achievements: [
      { id: "a1", icon: "🏆", title: "ICPC World Finals 2024 — 2nd Place", date: "Apr 2024" },
      { id: "a2", icon: "🎮", title: "Steam Game — 15k Wishlists", date: "Jan 2024" },
      { id: "a3", icon: "⭐", title: "Codeforces Grandmaster", date: "Feb 2024" },
    ],
    socials: [
      { platform: "GitHub", handle: "@kenjin", url: "#" },
      { platform: "X", handle: "@kenji_cp", url: "#" },
    ],
  },
  {
    id: "4",
    rank: 4,
    avatar: "🎨",
    name: "Amara Osei",
    handle: "@amara.o",
    country: "Ghana",
    flag: "🇬🇭",
    university: "Ashesi University",
    niScore: 9104,
    scoreChange: 201,
    categories: ["creative", "social"],
    tags: ["creative", "social"],
    bio: "UX designer & design systems lead. Creating accessible products for 1B+ users across Africa.",
    followers: 18900,
    following: 423,
    rankPercentile: "Top 0.08%",
    joinedDate: "Jan 2024",
    skills: [
      { label: "Design", value: 98, color: "#F5A200" },
      { label: "UX", value: 95, color: "#9333EA" },
      { label: "Code", value: 72, color: "#1A56FF" },
    ],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 83, weight: "25%", description: "GPA, coursework, academic awards", color: "#1A56FF", items: ["GPA 3.8/4.0", "Design Excellence Award"] },
      { id: "research", name: "Research", icon: "🔬", score: 65, weight: "25%", description: "Papers, citations, contributions", color: "#00BE6A", items: ["UX Research Lead", "CHI Workshop 2024"] },
      { id: "code", name: "Code", icon: "💻", score: 71, weight: "20%", description: "GitHub activity, open source", color: "#9333EA", items: ["Open Design System", "React Component Lib"] },
      { id: "creator", name: "Creator", icon: "✨", score: 98, weight: "15%", description: "Content, courses, tutorials", color: "#F5A200", items: ["18k Followers", "Design Newsletter 10k+", "Dribbble Top Shot"] },
      { id: "social", name: "Social", icon: "🤝", score: 95, weight: "15%", description: "Community, mentoring, impact", color: "#FF4500", items: ["Africa Design Lead", "Mentor 40+ Designers"] },
    ],
    achievements: [
      { id: "a1", icon: "🏅", title: "Google UX Design Residency", date: "Jul 2024" },
      { id: "a2", icon: "🎨", title: "Awwwards Site of the Year", date: "Dec 2024" },
      { id: "a3", icon: "🌍", title: "Forbes 30 Under 30 Africa", date: "Mar 2024" },
    ],
    socials: [
      { platform: "Dribbble", handle: "@amara_ux", url: "#" },
      { platform: "LinkedIn", handle: "amara-osei", url: "#" },
      { platform: "X", handle: "@amara_designs", url: "#" },
    ],
  },
  {
    id: "5",
    rank: 5,
    avatar: "🧬",
    name: "Lena Volkova",
    handle: "@lena.v",
    country: "Germany",
    flag: "🇩🇪",
    university: "TU Munich",
    niScore: 8897,
    scoreChange: 56,
    categories: ["research", "tech"],
    tags: ["research", "tech"],
    bio: "Quantum computing researcher. Building fault-tolerant quantum algorithms for drug discovery.",
    followers: 6100,
    following: 89,
    rankPercentile: "Top 0.1%",
    joinedDate: "Apr 2024",
    skills: [
      { label: "Research", value: 96, color: "#00BE6A" },
      { label: "Math", value: 99, color: "#1A56FF" },
      { label: "Code", value: 87, color: "#9333EA" },
    ],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 96, weight: "25%", description: "GPA, coursework, academic awards", color: "#1A56FF", items: ["PhD Quantum Computing", "DAAD Scholar", "Summa Cum Laude"] },
      { id: "research", name: "Research", icon: "🔬", score: 94, weight: "25%", description: "Papers, citations, contributions", color: "#00BE6A", items: ["6 Papers", "89 Citations", "Physical Review Letters"] },
      { id: "code", name: "Code", icon: "💻", score: 85, weight: "20%", description: "GitHub activity, open source", color: "#9333EA", items: ["Qiskit Contributor", "Open Quantum Tools"] },
      { id: "creator", name: "Creator", icon: "✨", score: 61, weight: "15%", description: "Content, courses, tutorials", color: "#F5A200", items: ["Quantum YouTube: 8k subs"] },
      { id: "social", name: "Social", icon: "🤝", score: 72, weight: "15%", description: "Community, mentoring, impact", color: "#FF4500", items: ["QC Community Organizer", "EuroQuantum Lead"] },
    ],
    achievements: [
      { id: "a1", icon: "⚛️", title: "Physical Review Letters Publication", date: "Aug 2024" },
      { id: "a2", icon: "🏆", title: "IBM Quantum Excellence Award", date: "Oct 2024" },
      { id: "a3", icon: "🎓", title: "DAAD Fellowship", date: "Sep 2023" },
    ],
    socials: [
      { platform: "GitHub", handle: "@lenavolkova", url: "#" },
      { platform: "Scholar", handle: "Lena Volkova", url: "#" },
    ],
  },
  {
    id: "6",
    rank: 6,
    avatar: "🚀",
    name: "Marcus Chen",
    handle: "@marcus.c",
    country: "Singapore",
    flag: "🇸🇬",
    university: "NUS",
    niScore: 8743,
    scoreChange: 118,
    categories: ["tech", "social"],
    tags: ["tech", "social"],
    bio: "Founder & CTO. Built 3 startups, 2 exits. Now building developer tooling at scale.",
    followers: 22100,
    following: 567,
    rankPercentile: "Top 0.12%",
    joinedDate: "Jan 2024",
    skills: [
      { label: "Startup", value: 97, color: "#FF4500" },
      { label: "Code", value: 93, color: "#1A56FF" },
      { label: "Ops", value: 88, color: "#00BE6A" },
    ],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 81, weight: "25%", description: "GPA, coursework, academic awards", color: "#1A56FF", items: ["CS Honors NUS", "Start-up Module Lead"] },
      { id: "research", name: "Research", icon: "🔬", score: 58, weight: "25%", description: "Papers, citations, contributions", color: "#00BE6A", items: ["1 Industry Paper", "10 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 93, weight: "20%", description: "GitHub activity, open source", color: "#9333EA", items: ["2,100 Contributions", "Popular OSS Projects"] },
      { id: "creator", name: "Creator", icon: "✨", score: 89, weight: "15%", description: "Content, courses, tutorials", color: "#F5A200", items: ["22k Followers", "Tech Newsletter 14k"] },
      { id: "social", name: "Social", icon: "🤝", score: 94, weight: "15%", description: "Community, mentoring, impact", color: "#FF4500", items: ["2 Startup Exits", "Angel Investor", "Tech Mentor 50+"] },
    ],
    achievements: [
      { id: "a1", icon: "🚀", title: "2x YC-Backed Startup Founder", date: "2023" },
      { id: "a2", icon: "💰", title: "$4M Seed Round Closed", date: "Jun 2024" },
      { id: "a3", icon: "🌏", title: "Forbes Asia 30 Under 30", date: "Jan 2024" },
    ],
    socials: [
      { platform: "X", handle: "@marcusbuilds", url: "#" },
      { platform: "LinkedIn", handle: "marcus-chen-sg", url: "#" },
      { platform: "GitHub", handle: "@marcusc", url: "#" },
    ],
  },
  {
    id: "7",
    rank: 7,
    avatar: "📡",
    name: "Priya Nair",
    handle: "@priya.n",
    country: "India",
    flag: "🇮🇳",
    university: "IISc Bangalore",
    niScore: 8521,
    scoreChange: 0,
    categories: ["research", "tech"],
    tags: ["research", "tech"],
    bio: "Wireless systems researcher. Working on next-gen 6G protocols at IISc.",
    followers: 4300,
    following: 201,
    rankPercentile: "Top 0.15%",
    joinedDate: "May 2024",
    skills: [
      { label: "Research", value: 94, color: "#00BE6A" },
      { label: "Systems", value: 91, color: "#1A56FF" },
      { label: "Math", value: 96, color: "#9333EA" },
    ],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 95, weight: "25%", description: "GPA, coursework, academic awards", color: "#1A56FF", items: ["PhD IISc", "Prime Minister Research Fellow", "Gold Medal"] },
      { id: "research", name: "Research", icon: "🔬", score: 93, weight: "25%", description: "Papers, citations, contributions", color: "#00BE6A", items: ["5 IEEE Papers", "72 Citations", "IEEE Globecom Best Paper"] },
      { id: "code", name: "Code", icon: "💻", score: 79, weight: "20%", description: "GitHub activity, open source", color: "#9333EA", items: ["MATLAB Toolbox OSS", "Python SDR Tools"] },
      { id: "creator", name: "Creator", icon: "✨", score: 55, weight: "15%", description: "Content, courses, tutorials", color: "#F5A200", items: ["Technical Blog: 3k readers"] },
      { id: "social", name: "Social", icon: "🤝", score: 71, weight: "15%", description: "Community, mentoring, impact", color: "#FF4500", items: ["IEEE Student Lead", "Lab Mentor"] },
    ],
    achievements: [
      { id: "a1", icon: "📡", title: "IEEE Globecom Best Paper Award", date: "Dec 2024" },
      { id: "a2", icon: "🎓", title: "Prime Minister Research Fellowship", date: "Aug 2023" },
      { id: "a3", icon: "🏅", title: "Gold Medal — IISc ECE", date: "May 2023" },
    ],
    socials: [
      { platform: "Scholar", handle: "Priya Nair", url: "#" },
      { platform: "LinkedIn", handle: "priya-nair-iisc", url: "#" },
    ],
  },
];

export const TICKER_ITEMS = [
  { text: "Aryan Kapoor climbed +142 pts this week", change: "+142" },
  { text: "Amara Osei trending in Creative category", change: "+201" },
  { text: "New verified: Sofia Martínez · MIT", change: "✓" },
  { text: "Marcus Chen crossed 8,700 NI Score", change: "+118" },
  { text: "2,847 new verifications this month", change: "🔥" },
  { text: "Leaderboard update: 1,284 rank changes today", change: "↑" },
  { text: "Priya Nair — IEEE Best Paper Award verified", change: "✓" },
  { text: "Kenji Nakamura: ICPC World Finals #2 confirmed", change: "✓" },
];
